### ISSUE TITLE
request for discussion: enable static non-moving points?

### ISSUE THREAD

**Issue by r2evans** [mbedward/packcircles#1]
Michael,

Thanks for making your code available. I've been absent-mindedly looking for ways to push/repel scatterplot labels so that the labels do not at all overlap. However, most of the solutions I've found are graphics-specific (such as [directlabels](http://directlabels.r-forge.r-project.org/)), meaning that they won't work with my base-graphics needs. (I'm not averse to `ggplot2` or `lattice`, but (1) I'm much more familiar with base, and (2) I'm adding on to an already-functional non-trivial tool that would take considerably longer to convert into `ggplot2`.)

In addition to your TODO item of "other bounding shapes", I'd like to suggest discussion of moveable-versus-unmoveable points. Consider a set of points/shapes that cannot be moved but they should repel just the same. I don't think arbitrarily increasing their weight is appropriate, since they would still move each other, and that may cause unnecessarily strong repelling forces on the moveable shapes.

Is this a direction that interests you in your development here?

Thanks for the discussion.

~r2

**Comment by mbedward** [comment]
That's a great suggestion - thanks !  I'm happy to look into that and pull requests are welcome.

For your labelling problem you would also want to turn off the coordinate wrapping that is presently assumed.

**Comment by r2evans** [comment]
Honestly, I'm so packed with other stuff, I saw this and saw the potential but, since it didn't do what I needed immediately, I haven't looked at the source code yet. I think a generic solution that deals generically with coordinate-space (bounded or not) would be much easier to work into multiple plotting solutions, including `ggplot2`, `lattice`, and of course `base` -- this is why I would like to see your package expanded _just a little_ and it'll become my go-to for this need (which comes up more often -- and is stiff-armed -- all-too-often in my work).

I'll let you know if/when I can look at the code.

**Comment by mbedward** [comment]
Commit f5018a79481c7ec537a4dc8baf305067e6cb0aa6 adds an optional weights argument to the circleLayout function. The argument is a numeric vector with values in the range [0,1]. 0 indicates that a circle is fixed while 1 indicates normal movement. See docs for circleLayout. Feedback welcome.
