### ISSUE TITLE
Fill same colour for matching bubbles?

### ISSUE THREAD

**Issue by ceci-m-c** [mbedward/packcircles#5]
Hi, I am using this package to make bubble charts similar to what's pictured below. I am wondering if there is any way to fill bubbles that have the same name so they have the same colour as each other (i.e., all Coccomyxa bubbles would be darker green and all Trebouxia bubbles would be lighter green).

```r
label34 <- c("Coccomyxa", "Coccomyxa", "Trebouxia", "Coccomyxa", "Trebouxia", "Trebouxia", "Trebouxia", "Trebouxia")

p <- circleProgressiveLayout(ASVtab[474:481, 13])
d <- circleLayoutVertices(p)

ggplot(d, aes(x, y)) + 
  geom_polygon(aes(group = id, fill = id),
               colour = "black", show.legend = FALSE) +
  geom_text(data = p, aes(x, y), label = label34)+
  scale_fill_distiller(palette = "Greens") +
  theme_void()
``` 

![CC034Xyloschistes_p](https://github.com/mbedward/packcircles/assets/163098825/3388cb18-eb2e-45d1-97f0-76540bad672b)

Please let me know if this a question better for somewhere else

**Comment by mbedward** [comment]
I think the example near the end of the package vignette 'Progressive circle packing' might be what you are looking for. It includes ggplot code to fill circles with colours specified in the input data via the `scale_fill_manual` function. Please let me know if this works for you.

**Comment by ceci-m-c** [comment]
Hi, yes I found this to work. Only need to alter `fill = id` -> `fill = as.factor(id)` as `scale_fill_manual` does not accept continuous variables.

**Comment by mbedward** [comment]
Thanks. Glad to hear you got it working.
